<?php
// module/Photo/view/photo/photo/edit.phtml:

$title = 'Edit photo';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$title = $form->get('title');
$title->setAttribute('class', 'form-control');
$title->setAttribute('value', $photo->getTitle());
$title->setAttribute('placeholder', 'Photo title');

$desc = $form->get('description');
$desc->setAttribute('class', 'form-control');
$desc->setValue($photo->getDescription());
$desc->setAttribute('placeholder', 'Photo description');

$picture = $form->get('picture');
$picture->setAttribute('class', 'form-control');
$picture->setAttribute('placeholder', 'Photo to upload');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('photo', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($title) ?>
    <?= $this->formElement($title) ?>
    <?= $this->formElementErrors()->render($title, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($desc) ?>
    <?= $this->formElement($desc) ?>
    <?= $this->formElementErrors()->render($desc, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($picture) ?>
    <?= $this->formElement($picture) ?>
    <?= $this->formElementErrors()->render($picture, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();