<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

$title = 'Mes photos';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a class="btn btn-outline-primary" href="<?= $this->url('photo', ['action' => 'add']) ?>"><span class="glyphicon glyphicon-plus"></span><i class="fa-solid fa-plus"></i> Ajouter une photo</a>
</p>



<div class="d-flex flex-wrap">
    <?php foreach($photos as $photo): ?>
        <div class="card ml-2 mr-2" style="width: 18rem;">
            <img class="card-img-top" src="<?= $photo->getPath() ?>" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title"><?= $photo->getTitle() ?></h5>
                <p class="card-text"><?= $photo->getDescription() ?></p>
                <a href="<?= $this->url('photo', ['action' => 'edit', 'id' => $photo->getId()]) ?>" class="btn btn-primary"><i class="fa-solid fa-pen-to-square"></i></a>
                <a href="<?= $this->url('photo', ['action' => 'delete', 'id' => $photo->getId()]) ?>" class="btn btn-danger"><i class="fa-solid fa-trash"></i></a>
            </div>
        </div>

    <?php endforeach; ?>
</div>