<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var \Laminas\Form\Element\Image $image
 */

$title = 'Mes photos';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('photo', ['action' => 'add']) ?>">Ajouter une photo</a>
</p>

<div class="d-flex flex-wrap">
    <?php foreach($photos as $photo): ?>
        <div class="card ml-2 mr-2" style="width: 18rem;">
            <img class="card-img-top" src="<?= $photo->getPath() ?>" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title"><?= $photo->getTitle() ?></h5>
                <p class="card-text"><?= $photo->getDescription() ?></p>
                <a href="<?= $this->url('photo', ['action' => 'edit', 'id' => $photo->getId()]) ?>" class="btn btn-primary">Edit</a>
                <a href="<?= $this->url('photo', ['action' => 'delete', 'id' => $photo->getId()]) ?>" class="btn btn-danger">Delete</a>
            </div>
        </div>

    <?php endforeach; ?>
</div>


<!--<table class="table">
<tr>
    <th>Titre</th>
    <th>Description</th>
    <th>Chemin</th>
    <th>Utilisateur</th>
    <th></th>
</tr>
<?php /*if(count($photos) > 0){ */?>
    <?php /*foreach ($photos as $photo) : */?>
        <tr>
            <td><?/*= $this->escapeHtml($photo->getTitle()) */?></td>
            <td><?/*= substr($this->escapeHtml($photo->getDescription()), 0, 15).(strlen($photo->getDescription()) > 15 ? "..." : "") */?></td>
            <td><?/*= $this->escapeHtml($photo->getPath()) */?></td>
            <td><?/*= $this->escapeHtml($photo->getUser()->getFullName()) */?></td>
            <td>
                <a href="<?/*= $this->url('photo', ['action' => 'edit', 'id' => $photo->getId()]) */?>">Edit</a>
                <a href="<?/*= $this->url('photo', ['action' => 'delete', 'id' => $photo->getId()]) */?>">Delete</a>
            </td>
        </tr>
    <?php /*endforeach; */?>
<?php /*} else { */?>
    <tr>
        <td colspan="5">
            <div class="alert alert-info" role="alert">
                Aucune photo enregistrée ...
            </div>
        </td>
    </tr>
<?php /*} */?>

</table>-->