<?php

/**
 *
 * module/security/view/auth/auth/index.phtml
 *
 * This file has been generated with LaminasGen
 * https://github.com/ThomasLeconte/laminas-gen
 *
 */

$title = 'Access denied';
$this->headTitle($title);
?>
    <h2>Authentification requise pour accéder à cette page</h2>
    <div class="container">
        <div class="row">
            <div class="col">
                <a class="btn btn-primary" href="<?= $this->url("login") ?>">Se connecter</a>
                <a class="btn btn-warning" href="<?= $this->url('signup') ?>">S'enregistrer</a>

            </div>
        </div>
    </div>
<?php

