<?php

/**
 *
 * module/security/view/auth/auth/index.phtml
 *
 * This file has been generated with LaminasGen
 * https://github.com/ThomasLeconte/laminas-gen
 *
 */

$title = 'SharePhotos - Accès refusé';
$this->headTitle($title);
?>
    <h2>Vous devez être authentifié(e) pour accéder à cette page !</h2>
    <a class="btn btn-primary" href="<?= $this->url("login") ?>">S'identifier ...</a>
<?php

