<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 *
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                                'rel' => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico'
                            ])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
        <script src="https://kit.fontawesome.com/1a18b82127.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button
                        class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">

                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <img src="https://zupimages.net/up/22/25/bjdo.png" alt="...">
                    <ul class="navbar-nav">
                        <?php if(isset($_SESSION["user"])){ ?>
                            <li class="nav-item">
                                <span class="nav-link">Bonjour <?= $_SESSION["user"]->getFullName() ?></span>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="<?= $this->url('home') ?>">
                                    Photos <span class="sr-only">(current)</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= $this->url('galerie') ?>">
                                    Galeries
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= $this->url('commande') ?>">
                                    Commandes
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= $this->url('logout') ?>">
                                    <i class="fa-solid fa-right-from-bracket"></i> Déconnexion
                                </a>
                            </li>
                        <?php }else{ ?>
                        <!-- <li class="nav-item">
                                <a class="nav-link" href="<?= $this->url('login') ?>">
                                    Connexion
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= $this->url('signup') ?>">
                                    Inscription
                                </a>
                            </li>-->
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>
                    &copy; <?= date('Y') ?>
                    2T-Innovation, CAI
                </p>
            </footer>
        </div>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
    </body>
</html>
